user:
  login: Логин
  password: Пароль
  name: Фамилия

home-url: "https://contest.solutions/.../..."

# Язык в контесте. Возможные варианты:
locale: russian
# locale: english
# locale: kazakh
# locale: ukrainian

features:
  enable-auto-tests: true # Нужно ли запускать тесты при отправке?
  enable-auto-formatting: true # Нужно ли запускать форматирование при отправке?
