name: Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: Run tests
      run: nix develop --command bash -c "nix-shell nix/shell_templates/all.nix --command 'python -m unittest discover tests'"
